FROM python:3.9

COPY ./requirements.txt /etc/requirements.txt

RUN pip3 install --upgrade pip && pip3 install -r /etc/requirements.txt

COPY . /app
WORKDIR /app

CMD celery -A university worker -l info
