# Generated by Django 3.2.8 on 2021-10-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='Lectures',
            new_name='Lecture',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
