# Generated by Django 3.2.8 on 2021-10-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211024_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
